flutter:
  - 'flutter_app/**'

backend:
  - 'server/**'

ci:
  - '.github/**'

docs:
  - '**/*.md'

database:
  - 'BD/**'
  - 'server/sql/**'

config:
  - '.gitignore'
  - '.gitattributes'
  - '*.yml'
  - '*.yaml'
